
package com.soap.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReceivePolicyPkgImpService", targetNamespace = "http://cxfcenter.web.com/", wsdlLocation = "http://api.et361.com/Service/queryPolicyService?wsdl")
public class ReceivePolicyPkgImpService
    extends Service
{

    private final static URL RECEIVEPOLICYPKGIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECEIVEPOLICYPKGIMPSERVICE_EXCEPTION;
    private final static QName RECEIVEPOLICYPKGIMPSERVICE_QNAME = new QName("http://cxfcenter.web.com/", "ReceivePolicyPkgImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.et361.com/Service/queryPolicyService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVEPOLICYPKGIMPSERVICE_WSDL_LOCATION = url;
        RECEIVEPOLICYPKGIMPSERVICE_EXCEPTION = e;
    }

    public ReceivePolicyPkgImpService() {
        super(__getWsdlLocation(), RECEIVEPOLICYPKGIMPSERVICE_QNAME);
    }

    public ReceivePolicyPkgImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVEPOLICYPKGIMPSERVICE_QNAME, features);
    }

    public ReceivePolicyPkgImpService(URL wsdlLocation) {
        super(wsdlLocation, RECEIVEPOLICYPKGIMPSERVICE_QNAME);
    }

    public ReceivePolicyPkgImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVEPOLICYPKGIMPSERVICE_QNAME, features);
    }

    public ReceivePolicyPkgImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceivePolicyPkgImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IReceivePolicyPkg
     */
    @WebEndpoint(name = "ReceivePolicyPkgImpPort")
    public IReceivePolicyPkg getReceivePolicyPkgImpPort() {
        return super.getPort(new QName("http://cxfcenter.web.com/", "ReceivePolicyPkgImpPort"), IReceivePolicyPkg.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IReceivePolicyPkg
     */
    @WebEndpoint(name = "ReceivePolicyPkgImpPort")
    public IReceivePolicyPkg getReceivePolicyPkgImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxfcenter.web.com/", "ReceivePolicyPkgImpPort"), IReceivePolicyPkg.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVEPOLICYPKGIMPSERVICE_EXCEPTION!= null) {
            throw RECEIVEPOLICYPKGIMPSERVICE_EXCEPTION;
        }
        return RECEIVEPOLICYPKGIMPSERVICE_WSDL_LOCATION;
    }

}
